### PR TITLE
Change of DFI-kernel and dfi-sinc-task

### PR DESCRIPTION
**Pull request by GGoek**
Edited the dfi.cl file due to my project, which inlcluds the mirroring part
(hermitian symmetry). Therefore the dfi-sinc-task.c needed a little
change, since less working groups are needed.

### CODE REVIEW

**Comment by matze** [comment]
There is a problem building the filter:

```
/home/travis/build/ufo-kit/ufo-filters/src/ufo-dfi-sinc-task.c: In function ‘ufo_dfi_sinc_task_process’:
/home/travis/build/ufo-kit/ufo-filters/src/ufo-dfi-sinc-task.c:258:46: error: ‘raster_size2’ undeclared (first use in this function)
```

I don't know if it's a typo or an undeclared variable called `raster_size2` but before merging this needs to be fixed.

**Comment by GGoek** [comment]
I have forgotten to divide it by 2, it should have meant ->  
int interp_grid_rows = (int) ceil ((float) ((raster_size/2)+1) / (float)BLOCK_SIZE);

**Comment by matze** [comment]
Can you update the file, commit and push the second commit? I tried but I cannot push to this pull request because you opened it.

**Comment by matze** [comment]
:+1:

**Pull request merged**
