### PR TITLE
Add ufo-filterhelp tool to get a list of available filters and maybe some useful infos

### PR DESCRIPTION
**Pull request by TimoDritschler**
I was pretty overwhelmed by the amount of filters and the naming convention from `libufodetectedge.so` to `detect-edge` as the filter-names were very confusing to me, because of the removal of dashes and such. I know that a little bit of intelligence can help you guess where the dashes are supposed to go, but still there is cases where it is not quite obvious (like `ring-pattern` and `ringwriter`).

At first I used the `ufo_plugin_manager` to give me a list of know filters, but those ones are already stripped of the dashes in their names as well. So, I have whipped up a small CMAKE integrated script which generates a small `ufo-filterhelp` executable which gives you the correct naming conventions.  
Its just a quick idea, but maybe we can improve this to add _glib-ified_ listing of properties? 

For example:

```
$>ufo-filterhelp write
'write' filter exposes the following properties:
-- filename 
Type: String
Info: "Filename filename string"
Description: "filename string of the path and filename. If multiple files are written it must contain a '%i' specifier denoting the current count"  

-- append
Type: Boolean
Info: "If true the data is appended, otherwise overwritten"
Description: "If true the data is appended, otherwise overwritten"

-- bits 
Type: Unsigned Int
Info: "Number of bits per sample"
Description: "Number of bits per sample. Possible values in [8, 16, 32]."

$>
```

But, like I said, its just a quick idea. What do you think?

### CODE REVIEW

**Comment by matze** [comment]
Honestly, I'd rather update the [documentation](http://ufo-filters.readthedocs.org/en/master/) and keep it up to date. Having correct names, information and hints is much more benefitial in the long run I suppose. But maybe @tfarago has some thoughts about that.

**Comment by TimoDritschler** [comment]
The importance of a good documentation is out of the question, but for just getting that additional quick info like: "What was that parameter called again?" it think it would be rather useful.
This is purely to provide quick access to what is right there, in the code, anyways. It is not meant to replace any kind of documentation. So I don't really see your point. You would still have both, documentation and quick-help.

**Comment by tfarago** [comment]
I actually missed this already a couple of times when playing with `ufo-launch`. It is very convenient not to browse any docs when working on the command line, so, I'd say let's go for it.

**Comment by matze** [comment]
> It is not meant to replace any kind of documentation. So I don't
> really see your point. You would still have both, documentation and quick-help.

Well I don't see the point in having a secondary program which I'd have
to call in a separate shell. Then I'd actually favor a
script/program/whatever that integrates with bash completion to provide
filter and parameter names.

**Comment by TimoDritschler** [comment]
I get the point about bash completion. That would be a nice thing to have. 
And on the point of having to use a separate shell: In the current case you would need a separate window/browser to look into the documentation or, again, another shell to look into the text-file documentations. Not that much of a difference, isn't it? :smile:

**Pull request closed without merging**
