### PR TITLE
Upgrade downsample

### PR DESCRIPTION
**Pull request by tfarago**
We have been postponing this for too long. I changed the naming because now the filter can scale both up and down. Also the factor is now used as a multiplier from the final shape perspective because it is much more intuitive, e.g.:
```bash
ufo-launch dummy-data width=2048 height=2048 number=1000 ! rescale factor=2 interpolation=linear ! null
```
gives you images twice as large.

And of course, we finally have linear interpolation.

To myself: *Don't forget to fix the test in ufo-core afterwards!*

### CODE REVIEW

**Comment by matze** [comment]
Looks good to me :+1:

@chuan137: this might be also interesting for you.

**Comment by chuan137** [comment]
@matze yeap, thanks Matthias.

**Comment by matze** [comment]
@tfarago: one question, why did you settle with `nearest` as the default value? I noticed that the upscaling quality is … well … bad. I just tested the performance (not with `time` but the `--trace` flag) and there is no difference between `linear` and `nearest` on both Fermi and Maxwell, hence I'd suggest to change the default from `nearest` to `linear` if that's okay for you.

**Comment by tfarago** [comment]
Fine by me.

**Pull request merged**
