### PR TITLE
New filters added

### PR DESCRIPTION
**Pull request by ldorofeeva**
I have added a couple of useful filters, namely:
- remove_outliers ( logic is very similar to one in ImageJ, however the patch is quadratic as in ufo median filter, not round );
- absorptivity and fix_nan_and_inf, that can be used in ufo pipeline;
- projection filter bh3.

### CODE REVIEW

**Comment by ldorofeeva** [comment]
Hi,
I have just found your wonderful calculate filter, so there's no need to add absorptivity and fix_nan_and_inf.

**Comment by matze** [comment]
So, just the first two commits are relevant then?

**Comment by matze** [comment]
By the way, yes the `calculate` filter is useful for this case but we should code such behaviour into a default kernel as well. Discussion concerning this topic can be followed at #150.

**Comment by matze** [comment]
So, I cherry-picked the two commits into the master branch but will wait for either @tfarago or @milkdrop to comment on why bh3 should be made the default frequency filter before closing this PR.

**Comment by tfarago** [comment]
Is that a future proposal or has it been changed? I don't see it here. As a default value I would definitely keep the `RAMP_FROMREAL`.

**Comment by ldorofeeva** [comment]
Yes, only two first commits are relevant.
Regarding bh3 - I will just add it as a choice to tofu/config.py.

**Comment by milkdrop** [comment]
Reconstruction will work somewhat slower than unwindowed FBP (needs to compute an extra sum of sin and cos), however application of the Blackman-Harris-3 window should in general produce images of slightly better quality and suppress the high frequency noise (F. Harris, On the use of windows for harmonic analysis with the discrete Fourier transform, IEEE 1978). So if the super-fast computing is not the priority, then I would definetely use it.
Note that it also make no sense at all to mix BH3 window with f.i. Butterworth window, since the effect of the latter is much stronger anyways.

**Comment by tfarago** [comment]
I think the question here is, are the default values in the framework supposed to initialize the filters so that they are usable with the _simplest_ settings or the ones which produce the _highest quality_ results. I was always programming for the first case, although I don't think we have ever explicitly discussed that...

**Comment by matze** [comment]
I'd like to close this PR but I see that the discussion is not really conclusive. So here are a few thoughts.

First: I doubt that the computation of Blackman-Harris-3 has any measurable performance impact, it's done once on a small 1D array. In fact, I think the default filter right now would have the largest but probably still negligible performance impact because it computes a 1D FFT as well.

Second: considering that none of the filters have any real performance impact, we should strive for the best result in all cases that does not require any user input (i.e. avoiding coming up with sensible parameter values). Both ramp and bh3 are parameterless so they fit the bill. Now which of the two gives the best quality is subject to the data. I suppose for synthetic data without noise, ramp will give  the most truthful representation of a reconstruction but in probably all real world cases some form of high-frequency noise attenuation cannot be that bad either. So, I am leaning towards BH3 unless @tfarago has really convincing arguments against it.

**Comment by matze** [comment]
So, all changes have been cherry-picked or incorporated via other means (NaN/inf, absorption correction via the `opencl` kernel), therefore I think we can close this.

**Pull request closed without merging**
