### PR TITLE
Add ZeroMQ pub/sub support

### PR DESCRIPTION
**Pull request by matze**
Hello all and especially @tfarago and @tekinbicer, this is the PR that will eventually allow us to integrate UFO pipelines with (almost) arbitrary ZeroMQ producers and consumers. The main addition of this PR are two tasks `zmq-pub`, a sink that publishes data, and `zmq-sub`, a source that subscribes to data. As of now, it is somewhat working with itself however there are numerous issues, that need to be solved before this can be merged and be useful in a broader sense.

## Protocol and serialization format

Right now, I [adapted](https://github.com/ufo-kit/ufo-filters/blob/5b9150637b98f8bc79b849c7cab111bbebaff0b1/src/ufo-zmq-common.h) Tekin's format to send the geometry for each item however a lot more properties need to be sent as well. Right now, I see two or three layers: the data type of an element (i.e. `dtype` in Numpy), the geometric description (number of dimensions, length of each dimension) and semantic description identifying the purpose (sinogram, projection, whatever). In my opinion the first two are absolutely required and should be part of every message received in order to correctly reconstruct the array by computing the size. The semantic description we could either implement as a type field or even better as a ZeroMQ prefix which would allow users to filter streams according to the type.

### Where to keep the standard

In case we agree on a standard, how do we handle it? Right now, this is just a struct in a header file and an informal protocol however for wider adoption there should be "neutral ground" where the specification is located.

## Multi-part messages

Real multi-part messages instead of struct embedding or copying would make sense for several reasons: First, communication would be cleaner to implement in the subscriber because we can logically separate receiving the description from the actual frame data and second it would make zero-copy send and receive pretty straightforward. As far as I can tell, this is only a semantic mechanism and does not necessarily mean two separate network frames.

## Lost messages

I have several problems with reliability: it's clear that the subscriber needs to be up and running before the publisher if he wants to do meaningful work (not so important for a viewer I guess but a reconstruction should receive all the projections :smile:) but this is easily solved via policies on a higher level. However, I also have low-level reliability problems. If I don't sleep a bit in the publisher, the messages will get lost on the way to the subscriber … this is not tolerable but as far as I can see *is* the status quo with the pub/sub pattern. @tekinbicer how do you cope with this? I see that you define some REQ/REP calls as well, do you roll your own PUB/SUB?

---

So I am curious to hear what you have to say and if you have other ideas as well!

### CODE REVIEW

**Comment by tekinbicer** [comment]
Great Matthias! 

I use sequence number (seq_number) to keep track of the messages. The pub socket increases the seq_number after each send, and subs expect these messages to be in order. Currently, I haven't implemented anything to recover lost messages, however a simple solution can be implementing sliding window at both pub and sub and temporarily store last _n_ messages. If there is any lost messages, they can be recovered from window.

I use req/rep sockets to synchronize pub/sub processes at the beginning of execution. This is the flow I have:
1. create/connect req/rep sockets
2. create/connect pub/sub sockets
3. handshake using req/rep before publishing any data
4. publish data
5. finalize using req/rep (might not be necessary, but nice to have if collecting performance numbers)

This is still not complete and messages can be lost. For _slow joiner_ problem, a better strategy is to extend step 3 so that req/rep exchanges messages till pub/subs are synched (see [this](http://zguide.zeromq.org/page:all#Node-Coordination)). For lost messages in step 4, 
 the problem is more complicated. Here, a simple (and probably naive) solution can be sending data up to the window size with pub/sub, then synch using req/rep sockets. If any missing message is detected (using seq_number), it can be resent from pub's window. If any replicated messages is received at the subs side (messages with same seq_number), they can simply be dropped.
Hopefully(!), synchronization cost would be low with sufficiently large window size.

At some point, we need to (de)serialize data properly, we might want to use something like ProtoBuffer on top of ZMQ.

**Comment by matze** [comment]
> Currently, I haven't implemented anything to recover lost messages, however a simple solution can be implementing sliding window at both pub and sub and temporarily store last n messages. If there is any lost messages, they can be recovered from window.

Hmm that loses the stateless appeal a bit. Especially since that requires an additional round trips to tell the publisher to start again from an earlier point in the window and the subscribers that *did* receive the data have to filter that out. But if it turns out to be the only option that works reliably, that will have to do. I'll make some more tests on real network hardware though, just tested locally on my laptop yesterday.

> At some point, we need to (de)serialize data properly, we might want to use something like ProtoBuffer on top of ZMQ.

I was looking into ProtoBuf but from what I can tell it does not seem to be very suitable for large data according to [this article](http://dbeck.github.io/5-lessons-learnt-from-choosing-zeromq-and-protobuf/). One option would be to use it for the header and send the frame data as a separate part.

**Comment by tfarago** [comment]
> Protocol and serialization format

I am not sure if the semantics really need to be there. The question is, is it likely that in one stream there will be more semantically different types, e.g. projections, sinograms? I mean subscriber anyway needs to connect somewhere and the port or whatever could indicate what the semantics are. Anyway, this is minor and since we need metadata it wouldn't hurt to have it there too...
I would then definitely use the pub-sub message envelopes, i.e. the multi-part messages.

> Where to keep the standard

I think proper description of the standard is enough in terms of metadata. However, if we opt for some more complex stuff like a second channel for controlling the stream that will be difficult. We could write the code in C and Python and make that separate repos, but the other languages I don't know... Who needs another language can chip in...

> Lost messages

This is nasty. The req/rep channel on top will complicate things and most importantly slow them down. Is there something else we could use instead of publish/subscribe?

**Comment by matze** [comment]
> I am not sure if the semantics really need to be there. The question is, is it likely that in one stream there will be more semantically different types, e.g. projections, sinograms?

Not necessarily that but for example depending what kind of data you transmit you want to transmit corresponding metadata as well. In Tekin's case, they send the rotation angle and center along with the projection. So you somehow have to know what you received.

**Comment by tfarago** [comment]
Yeah in that case I completely agree.

**Comment by matze** [comment]
I implemented prior synchronization with req/rep as proposed by Tekin and it works remarkably well and so far does not even require windows to keep up with the stream. Once connection is established no further messages are lost, so there must be some serious buffering going on behind the scene.

However, this approach has the obvious downside that the publisher now needs to know how many subscribers really have to receive the entire stream (the zmq guide is funny concerning that number: "This is just a magic number it gets from somewhere."). I added an `expected-subscribers` count to the `zmq-pub` which whoever is setting up the distributed system must set correctly. If it's too low, required subscribers might miss data, if it's too high the publisher might block forever or receive non-sync garbage messages.

I'd say for now the lost messages point is somewhat solved and I go back to the multi-part message and protocol design.

**Comment by tfarago** [comment]
> I implemented prior synchronization with req/rep as proposed by Tekin and it works remarkably well and so far does not even require windows to keep up with the stream. Once connection is established no further messages are lost, so there must be some serious buffering going on behind the scene.

Very good! But it would be good to have some assurance since dropping projections is not so nice.

> However, this approach has the obvious downside that the publisher now needs to know how many subscribers really have to receive the entire stream ...

But this just defeats the purpose of the whole pub-sub model. I get that we need it, just felt the urge to complain a bit :smile: On second thought, has no one ever used this model to process data and needed to be sure all the messages went through?? The message drops must be an implementation issue which should be solved on the proper place...

**Comment by matze** [comment]
> On second thought, has no one ever used this model to process data and needed to be sure all the messages went through?? The message drops must be an implementation issue which should be solved on the proper place...

This is by design and will never be "solved on the proper place". Here's what the guide says:

> Pub-sub is like a radio broadcast; you miss everything before you join, and then how much information you get depends on the quality of your reception. Surprisingly, this model is useful and widespread because it maps perfectly to real world distribution of information. Think of Facebook and Twitter, the BBC World Service, and the sports results.

The whole idea of ZeroMQ is in providing building blocks and mechanisms to form complete systems not solving each and every problem that might exist. And one must also keep in mind that this was developed with financial trading in mind, i.e. many, small messages not like us with few, large ones.

**Comment by matze** [comment]
> But it would be good to have some assurance since dropping projections is not so nice.

There are sequence numbers implemented, so we could at least detect a problem. But let's do some actual tests on real hardware to see what we really have to do.

**Comment by matze** [comment]
Okay here are some more observations and thoughts:

* Some form of synchronization is required during streaming. Depending on the bandwidth and message size I can outrun the subscribers at which point the send queue of the publisher overflows and messages get dropped. Our InfiniBand infrastructure is good enough to transmit 2048 projections of 16 MB each but it's already not working on our 10 GE system.
* ZeroMQ publishers can never block and don't have rate limits built in therefore this cannot be solved just using the ZeroMQ API.
* Rate-limiting can be implemented by waiting sufficiently long, however that requires precise measurement of the available bandwidth which could change all the time. Besides that being a fragile metric it requires constant "back-chatter" with the subscriber in order to measure the round-trip time.
* Adding the sliding window approach as proposed by Tekin could help, but I see two major problems besides being a relatively complex protocol: 1) it could waste quite some bandwidth with multiple subscribers, i.e. to fast subscribers who have actually seen the data already but have to skip it and 2) it  just might not work. That scenario happens if the subscribers are relatively slow and only realize drops when the publisher already reached the end of the ring buffer. At that time it can only playback the last `window_length` items. To make this robust for all cases means keeping *all* the items …

So, from my point of view pub/sub is not robust enough to deal with this high throughput scenario. The only working solution is manual distribution using blocking req/rep. In this case, the "subscribers" would request a data item from a service and wait to recv it. The "publisher" would keep a list of "subscribers" and send each of them a copy of the data (not to bad, there is the possibility to re-use data with zmq). However, that means losing builtin-in multicast functionality, loss of scalability and bandwidth.

**Comment by tfarago** [comment]
Nice summary. Although I am not happy with its implications... So if we want to be on the sage side regarding the number of projections and we want a reconstructor subscriber and data-writer subscriber, we drop the bandwidth by 2 because the publisher must send the same data over the same network twice. I think this is just not acceptable. The other solution with losing projections is not acceptable as well of course, so maybe this is just not the way to go in the end... But what is?

**Comment by matze** [comment]
I outlined in the last paragraph what my solution would be: fake the pub/sub mechanism with  request/reply. The publisher keeps a list of registered subscribers who are allowed to request data items. The publisher will continue with the data items as soon as all subscribers have received the data. The network protocol would look like this:

### Publisher

1. Open REP socket to handle registration and data requests (we could also use two but that requires threads …)
2. recv `expected-subscribers` registration requests to avoid slow-joiner problem
2.1 if instead we get a data request, reply with error and swear words
3. recv requests
3.1. If it is a registration request, add to the subscriber list
3.2. if it is a data request send the current item
3.2.2. if the current item was sent already, reply with error and swear words
4. if data is sent for each registered subscribers continue with the next item
5. send stop message to mark the end

### Subscribers

1. Open REQ socket to send registration and data requests
2. Compute a unique ID and send it to the publisher
3. Ask for data using the ID until we get the stop message

This should work alright, however as I said before this will prevent great scalability because the slowest subscriber will determine the throughput and if a malicious client does not ask for data we have to wait for ever or until a timeout wakes up the publisher. Any comments @tfarago and @tekinbicer?

**Comment by tfarago** [comment]
LGTM. If a subscriber starts before the publisher it has nowhere to connect to so it will time out and we can either throw an error or try again.

**Comment by tekinbicer** [comment]
@matze 
I think your method will work. Also, I don't think there is any issue in terms of the order of the starting side: any rep can start before any req or vice versa.

My main issues with this approach are scalability (as you mentioned) and the idea of blocking data source because of the receiver. For blocking the data source issue: there is probably little that can be done to fully eliminate synchs since we want to guarantee data transfers, but I think we should minimize this as much as possible. Probably, we can collect items in a buffer (buffer size is a configurable parameter where n=1 is single item) and send them all together in 3.2.

Eventually, I think we should move to a more asynch protocol than REQ/REP. We can probably extend REQ/REP with other sockets to do this. 

One suggestion I have is separating data transfer sockets from handshake socket(s), therefore if we would like to change the data transfer sockets later we don't need to mess up with the handshake side.

**Comment by matze** [comment]
As you can see, I implemented my approach yesterday and as predicted by Tekin and me, works reliably and subscribers do not have to wait beforehand for the connection. However, there are two pain points at the moment: 1) performance is abysmal and 2) batching data as proposed by Tekin is not helping for common cases.

I took our "standard case" of 2048×2048×2048×4 bytes, i.e. 32 GB of data. These could be 2k projections or 2k sinograms but for the sake of measurement it does not matter. Here's what I achieve on our InfiniBand but split in different ways to simulate the effect of batching:

| width | height | number | bsize (MB) | time (s) | throughput (MB/s) |
|------:|-------:|-------:|-----------:|---------:|------------------:|
| 256   | 2048   | 16384  | 2          | 54.58    | 611.6             |
| 512   | 2048   | 8192   | 4          | 53.16    | 628.2             |
| 1024  | 2048   | 4096   | 8          | 52.13    | 640.9             |
| 2048  | 2048   | 2048   | 16         | 53.13    | 628.6             |
| 4096  | 2048   | 1024   | 32         | 60.87    | 547.3             |
| 8192  | 2048   | 512    | 64         | 56.97    | 585.5             |
| 16384 | 2048   | 256    | 128        | 59.27    | 562.3             |

The standard case would be the row in the middle, i.e. some 630 MB/s which is already beyond break even. As you can see, batching more frames will yield lower performance. Besides that, `iperf` tells me that I should be able to get ~ 2.6 GB/s. That would be really nice, because all things considered data transfer would be a real bottle neck with our 4×GTX1080 Ti machine being able to process > 1 GB/s …

**Comment by tekinbicer** [comment]
@matze, I'm not sure but there might be additional steps to use ZMQ on infiniband. Is this with 1 server 1 client? Could you also check the bandwidth and latency with ZMQ perf tools? They should be under $ZMQ_HOME/perf/{local|remote}_thr

**Comment by matze** [comment]
As far as I know, ZMQ never had and never will have native InfiniBand support. All the tests were done IP-over-InfiniBand between two machines, that's right. But thanks for pointing out these perf tools, I will look into it and see how they perform.

**Comment by matze** [comment]
So, I measured with the ZMQ tools and that is a bit of a relieve:

| width | height | number | bsize (MB) | our    | perf   |
|------:|-------:|-------:|-----------:|-------:|-------:|
| 256   | 2048   | 16384  | 2          | 611.6  | 1709.2 |
| 512   | 2048   | 8192   | 4          | 628.2  | 1774.2 |
| 1024  | 2048   | 4096   | 8          | 640.9  | 1770.0 |
| 2048  | 2048   | 2048   | 16         | 628.6  | 1442.8 |
| 4096  | 2048   | 1024   | 32         | 547.3  | 1308.6 |
| 8192  | 2048   | 512    | 64         | 585.5  | 1140.9 |
| 16384 | 2048   | 256    | 128        | 562.3  | 1048.7 |

However, my initial observation still holds that after about 8 MB messages, throughput drops again. People from PSI have answered a mail from me and pointed me to their collection of repositories over at https://github.com/datastreaming. I will have a look at it tomorrow and evaluate the performance and possible integration points.

**Comment by tekinbicer** [comment]
Is the single msg sizes >2MB? If so, the transfers should actually hit max bandwidth already. It can also explain why there is no improvement with msg batching. Following are some tests that I did with our setting, where client and server are 1km apart and connected with 10Gig network.

throughput

.

**Comment by matze** [comment]
Yes, the `bsize` column refers to the size of a single message, so, my tests started at 2MB. However the 1774 MB/s = 14.2 Gbit/s is still far from the 19.1 Gbit/s reported by iperf and probably very far from what InfiniBand is capable of.

**Comment by tekinbicer** [comment]
I'm actually surprised that there is that much gap between ours vs. perf results. Is it easy to compile and test the code? I will try it, when I have a chance.

**Comment by matze** [comment]
Alright, so the current state works, fulfills one major requirement (never drop a message) but comes with a performance hit. I think for now I can live with that and I will now investigate what's going on on the format front. I had a look at the [PSI htypes spec](https://github.com/datastreaming/htypes) which looks pretty reasonable except for the JSON parsing part and that float is not part of their spec. Nevertheless, I think it makes sense to implement it and see how that affects performance.

**Comment by matze** [comment]
So, I squashed everything down to a single commit. It seemingly works alright but there is one open issue concerning the data format: although I now use PSI's header format, there is no specification on the protocol. So, I seriously doubt our pub/sub on req/rep implementation will work with their system because we need to do some book keeping to tell different subscribers apart which I think they just don't do. Anyway, I will merge this stuff for now, so we have at least something.

**Pull request merged**
